## Useful Documentation 

* https://docs.scipy.org/doc/numpy/ 

I'll refer to the main numpy through out this tutorial to point out specific sections that are relevant. 

### Running Jupyter Notebook Cells

Jupyter notebook is a great way to code iteratively. You can run a cell by clicking on the "Run" button above or you can use the shortcut by holding both "Shift + Enter" or "Shift + Return" (on mac) to run a cell. 

In [1]:
# <-- Means comment. I'll be using a lot of comments in this notebook.
# In this first cell we are going to import the libraries to use for
# creating our matrix. 

# numpy is imported as 'np' as a convention. 

import numpy as np 

In [2]:
# There are a couple data structures that we will rely on. As you may 
# know the basic data structure is a numpy array (vector).

In [3]:
# Basic building block of numpy as the array. Here we are going to use
# a list (denoted by square brackets) to create an array. 

# Creating list mylist
mylist = [1,2,3,4]

# Transforming mylist into an array:
myarray = np.array(mylist)

# Reviewing the output of myarray:
print(myarray)

# Still looks like a list but it is really a numpy array. Let's 
# take a closer look.

[1 2 3 4]


In [4]:
# Reviewing the data type of myarray:
print(type(myarray))

# Notice that the array is called an ndarray. This is short for 
# n-dimensional array. We can quickly find the shape (number of 
# rows vs columns) by using a numpy method. 

<class 'numpy.ndarray'>


In [5]:
# This means we have an array with four entries. We will use this later
# when verifying the shape of our randomly generated matrix. 
myarray.shape

(4,)

# Generating a Random Number

numpy provides a random class that generates real or integer numbers for us automatically. Let's take a look:

In [6]:
# How to generate a single real random number. By default it will
# generate a real number between 0 and 1.

np.random.random()

0.49093397495809843

In [7]:
# How to generate a single integer number. Here, the input determines
# what kind of data is returned to us. 

# If we enter one digit it will randomly select an integer from 0 to
# one less the provided number. For example, if we enter 3 into our
# randint method numpy will generate a number between 0 and 2. This 
# means it excludes the number we provided. Everything up to but not
# including the input will be randomly generated. 

np.random.randint(3)

2

# Generating a Random Matrix

In [14]:
# Creating a matrix of shape 1000 x 1000 with randomly generated 
# integers from 1 to 9 (included).

data = np.random.randint(low=1, high=10, size=(1000,1000))

# This randint method is nice because it does the work of creating
# the randomly generated matrix with lower and upper thresholds for
# the element values. Plus, it defines the size of the matrix for you.


In [13]:
# Preview of the data. Too big to display all of it. What jupyter does
# is it gives you a preview of the first few records and then skip
# to the tail (or end) and show you the last few records in the 
# matrix. 
data

array([[6, 3, 3, ..., 1, 4, 9],
       [4, 3, 8, ..., 3, 9, 8],
       [2, 8, 1, ..., 4, 9, 3],
       ...,
       [6, 9, 5, ..., 5, 9, 1],
       [6, 4, 4, ..., 5, 5, 3],
       [6, 1, 7, ..., 6, 4, 6]])

In [15]:
# The shape method returns a tuple of the (rows, columns) for 
# the data array. 

data.shape

(1000, 1000)

In [16]:
# Checking the maximum value in the matrix. We would expect 9 since
# we defined our high parameter as 10. Recall that it is up to but not
# including the high number. 

data.max()

9

In [17]:
# Verifying that the lowest integer in our matrix matches the 
# parameters above. 

data.min()

1

In [18]:
# This shows the first two arrays in the data matrix. 
data[:2]

array([[2, 1, 9, ..., 5, 3, 6],
       [3, 9, 4, ..., 7, 5, 3]])

# Finding Inverse of a Matrix

In [19]:
# Let's create a matrix called A.

A = np.random.randint(low=1, high=10, size=(1000,1000))

In [20]:
inv_A = np.linalg.inv(A)

In [21]:
inv_A

array([[ 0.04328592, -0.03678389,  0.08329243, ...,  0.10372268,
        -0.05212738, -0.00731597],
       [-0.09076974,  0.11044971, -0.16735512, ..., -0.21439707,
         0.10511214,  0.02323509],
       [-0.07937036,  0.06657925, -0.15968979, ..., -0.21176479,
         0.10235839,  0.01785967],
       ...,
       [-0.060117  ,  0.05175911, -0.09196752, ..., -0.13579766,
         0.07382596,  0.00934685],
       [-0.03802639,  0.04354612, -0.08200904, ..., -0.09927617,
         0.05916233, -0.008     ],
       [ 0.00998248,  0.00880859,  0.01470354, ...,  0.02622527,
        -0.00406968, -0.01968745]])

In [22]:
#  Okay, but how do we know that this actually generated the inverse
# of matrix A? We know that the dot product of a matrix and its inverse
# results in an identity matrix. 

np.dot(inv_A, A)

array([[ 1.00000000e+00,  1.01696429e-12,  1.40554235e-13, ...,
         3.24185123e-13,  6.65800748e-13,  3.88356014e-13],
       [-7.30082661e-13,  1.00000000e+00, -7.08766379e-13, ...,
        -4.58300065e-13, -6.94999613e-13, -5.95301586e-13],
       [ 1.19015908e-13,  9.14823772e-14,  1.00000000e+00, ...,
         1.95399252e-13,  8.03801470e-13,  2.73558953e-13],
       ...,
       [-1.42108547e-13, -2.71338507e-13, -7.59392549e-14, ...,
         1.00000000e+00, -9.62563362e-14, -1.28341782e-13],
       [-1.01252340e-13, -2.05613304e-13, -3.55271368e-14, ...,
        -1.67421632e-13,  1.00000000e+00, -1.04027897e-13],
       [ 2.28983499e-14,  1.70974346e-14,  1.01585407e-14, ...,
         1.92068583e-14,  3.13221671e-14,  1.00000000e+00]])